import type {
  Capability,
  CollectiveTemplate,
  CollectiveTemplateKey,
} from "./types.js";

const READ_CAPABILITIES: readonly Capability[] = [
  "guild.read",
  "constitution.read",
  "space.read",
  "actor.read",
  "membership.read",
  "role.read",
  "memory.read",
  "activity.read",
  "decision.read",
  "conversation.read",
  "announcement.read",
  "connection.read",
  "run.read",
  "event.read",
  "template.read",
  "relation.read",
  "lifecycle.read",
  "message.read",
  "contribution.read",
  "automation.read",
  "federation.read",
  "data.read",
  "inbox.read",
  // Compatibility aliases for the v1 adapters.
  "identity.read",
  "knowledge.read",
  "file.read",
  "work.read",
  "agent.read",
  "integration.read",
  "chronicle.read",
];

const PARTICIPATE_CAPABILITIES: readonly Capability[] = [
  ...READ_CAPABILITIES,
  "memory.create",
  "activity.create",
  "conversation.create",
  "decision.propose",
  "run.create",
  "connection.execute",
  "knowledge.create",
  "knowledge.propose",
  "file.create",
  "work.create",
  "agent.run",
  "integration.execute",
  "message.create",
  "contribution.correct",
];

const COORDINATE_CAPABILITIES: readonly Capability[] = [
  ...PARTICIPATE_CAPABILITIES,
  "activity.assign",
  "memory.govern",
  "decision.approve",
  "conversation.moderate",
  "announcement.manage",
  "run.approve",
  "run.stop",
  "knowledge.approve",
  "file.delete",
  "work.assign",
  "agent.approve",
  "agent.stop",
  "relation.manage",
];

const ADMINISTER_CAPABILITIES: readonly Capability[] = [
  ...COORDINATE_CAPABILITIES,
  "guild.manage",
  "space.manage",
  "actor.manage",
  "identity.manage",
  "membership.manage",
  "role.manage",
  "connection.manage",
  "integration.manage",
  "agent.manage",
  "template.manage",
  "lifecycle.manage",
  "automation.manage",
  "federation.manage",
  "data.manage",
];

function unique(capabilities: readonly Capability[]): readonly Capability[] {
  return [...new Set(capabilities)];
}

const templates: Record<CollectiveTemplateKey, CollectiveTemplate> = {
  blank: {
    key: "blank",
    name: "Blank Guild",
    description: "Start from neutral primitives and shape the Guild yourself.",
    labels: {
      members: "Members",
      member: "Member",
      human: "Human",
      agent: "Agent",
      service: "Service",
      guildActor: "Guild",
      memory: "Memory",
      memoryItem: "Memory",
      remember: "Remember",
      activity: "Activity",
      activityItem: "Activity",
      startActivity: "Start",
      decisions: "Decisions",
      decision: "Decision",
      history: "History",
      join: "Join",
      leave: "Leave",
      participant: "Participant",
      coordinator: "Coordinator",
    },
    roles: [
      { name: "Coordinator", capabilities: unique(ADMINISTER_CAPABILITIES) },
      { name: "Participant", capabilities: unique(PARTICIPATE_CAPABILITIES) },
      { name: "Observer", capabilities: unique(READ_CAPABILITIES) },
    ],
    activityTypes: ["task", "project", "event", "discussion", "creation", "investigation"],
    memoryTypes: ["fact", "document", "experience", "rule", "artifact", "learning"],
    decisionMethods: ["consent", "vote", "review", "custodian"],
    dashboardIntents: ["ask", "remember", "start", "review", "members"],
    workflows: [],
    suggestedAgent: null,
  },
  company: {
    key: "company",
    name: "Company",
    description: "A familiar company preset built on the same neutral substrate.",
    labels: {
      members: "People",
      member: "Team member",
      human: "Employee",
      agent: "AI assistant",
      service: "Integration",
      guildActor: "Partner organization",
      memory: "Knowledge",
      memoryItem: "Record",
      remember: "Document",
      activity: "Work",
      activityItem: "Task",
      startActivity: "Start work",
      decisions: "Approvals",
      decision: "Approval",
      history: "Audit log",
      join: "Onboard",
      leave: "Offboard",
      participant: "Staff",
      coordinator: "Manager",
    },
    roles: [
      { name: "Admin", capabilities: unique(ADMINISTER_CAPABILITIES) },
      { name: "Manager", capabilities: unique(COORDINATE_CAPABILITIES) },
      { name: "Staff", capabilities: unique(PARTICIPATE_CAPABILITIES) },
    ],
    activityTypes: ["project", "task", "maintenance", "investigation"],
    memoryTypes: ["manual", "rule", "document", "failure", "learning"],
    decisionMethods: ["custodian", "review"],
    dashboardIntents: ["review", "start", "ask", "remember", "members"],
    workflows: [
      { key: "manager-approval", name: "Manager approval", activityType: "task", memoryType: null, decisionMethod: "review" },
      { key: "manual-review", name: "Manual review", activityType: null, memoryType: "manual", decisionMethod: "review" },
    ],
    suggestedAgent: "Operations assistant",
  },
  community: {
    key: "community",
    name: "Community",
    description: "Coordinate members, discussions, events, and shared memory.",
    labels: {
      members: "Members",
      member: "Member",
      human: "Member",
      agent: "Community agent",
      service: "Community service",
      guildActor: "Partner community",
      memory: "Shared memory",
      memoryItem: "Community record",
      remember: "Preserve history",
      activity: "Initiatives",
      activityItem: "Initiative",
      startActivity: "Start an initiative",
      decisions: "Collective decisions",
      decision: "Decision",
      history: "Community history",
      join: "Join community",
      leave: "Leave community",
      participant: "Member",
      coordinator: "Moderator",
    },
    roles: [
      { name: "Steward", capabilities: unique(ADMINISTER_CAPABILITIES) },
      { name: "Moderator", capabilities: unique(COORDINATE_CAPABILITIES) },
      { name: "Member", capabilities: unique(PARTICIPATE_CAPABILITIES) },
    ],
    activityTypes: ["event", "discussion", "campaign", "ritual"],
    memoryTypes: ["conversation", "event", "experience", "rule", "learning"],
    decisionMethods: ["consent", "vote"],
    dashboardIntents: ["review", "members", "start", "ask", "remember"],
    workflows: [
      { key: "community-vote", name: "Community vote", activityType: "discussion", memoryType: null, decisionMethod: "vote" },
    ],
    suggestedAgent: "Community memory guide",
  },
  research: {
    key: "research",
    name: "Research Collective",
    description: "Join researchers and research agents around evidence and inquiry.",
    labels: {
      members: "Researchers",
      member: "Researcher",
      human: "Researcher",
      agent: "Research agent",
      service: "Research service",
      guildActor: "Research partner",
      memory: "Research memory",
      memoryItem: "Research note",
      remember: "Record findings",
      activity: "Studies",
      activityItem: "Study",
      startActivity: "Start research",
      decisions: "Research decisions",
      decision: "Research decision",
      history: "Research history",
      join: "Join research team",
      leave: "Leave research team",
      participant: "Researcher",
      coordinator: "Research lead",
    },
    roles: [
      { name: "Research lead", capabilities: unique(ADMINISTER_CAPABILITIES) },
      { name: "Researcher", capabilities: unique(PARTICIPATE_CAPABILITIES) },
      { name: "Reviewer", capabilities: unique(COORDINATE_CAPABILITIES) },
    ],
    activityTypes: ["study", "experiment", "investigation", "discussion"],
    memoryTypes: ["research", "data", "fact", "external", "failure", "learning"],
    decisionMethods: ["review", "consent"],
    dashboardIntents: ["ask", "start", "remember", "review", "members"],
    workflows: [
      { key: "peer-review", name: "Peer review", activityType: "study", memoryType: "research", decisionMethod: "review" },
      { key: "experiment", name: "Experiment", activityType: "experiment", memoryType: "data", decisionMethod: null },
    ],
    suggestedAgent: "Research synthesizer",
  },
  creator: {
    key: "creator",
    name: "Creator Collective",
    description: "Coordinate ideas, creation, editing, publishing, and provenance.",
    labels: {
      members: "Collaborators",
      member: "Collaborator",
      human: "Creator",
      agent: "Creative agent",
      service: "Publishing service",
      guildActor: "Creative partner",
      memory: "Creative memory",
      memoryItem: "Creative record",
      remember: "Save an idea",
      activity: "Creations",
      activityItem: "Creation",
      startActivity: "Start creating",
      decisions: "Reviews",
      decision: "Review",
      history: "Creative history",
      join: "Join collective",
      leave: "Leave collective",
      participant: "Creator",
      coordinator: "Creative lead",
    },
    roles: [
      { name: "Creative lead", capabilities: unique(ADMINISTER_CAPABILITIES) },
      { name: "Creator", capabilities: unique(PARTICIPATE_CAPABILITIES) },
      { name: "Editor", capabilities: unique(COORDINATE_CAPABILITIES) },
    ],
    activityTypes: ["creation", "project", "session", "campaign"],
    memoryTypes: ["artifact", "experience", "document", "learning"],
    decisionMethods: ["editorial", "consent"],
    dashboardIntents: ["start", "remember", "review", "members", "ask"],
    workflows: [
      { key: "editorial-review", name: "Editorial review", activityType: "creation", memoryType: "artifact", decisionMethod: "editorial" },
    ],
    suggestedAgent: "Editing companion",
  },
  "open-source": {
    key: "open-source",
    name: "Open Source Project",
    description: "Coordinate maintainers, contributors, services, and project history.",
    labels: {
      members: "Contributors",
      member: "Contributor",
      human: "Contributor",
      agent: "Coding agent",
      service: "Automation",
      guildActor: "Partner project",
      memory: "Project memory",
      memoryItem: "Project record",
      remember: "Document",
      activity: "Issues and initiatives",
      activityItem: "Issue",
      startActivity: "Open an issue",
      decisions: "Project decisions",
      decision: "Project decision",
      history: "Project history",
      join: "Join project",
      leave: "Leave project",
      participant: "Contributor",
      coordinator: "Maintainer",
    },
    roles: [
      { name: "Maintainer", capabilities: unique(ADMINISTER_CAPABILITIES) },
      { name: "Contributor", capabilities: unique(PARTICIPATE_CAPABILITIES) },
      { name: "Reviewer", capabilities: unique(COORDINATE_CAPABILITIES) },
    ],
    activityTypes: ["task", "project", "maintenance", "investigation", "discussion"],
    memoryTypes: ["document", "artifact", "decision", "failure", "learning"],
    decisionMethods: ["review", "consent", "custodian"],
    dashboardIntents: ["start", "review", "ask", "remember", "members"],
    workflows: [
      { key: "pull-request-review", name: "Pull request review", activityType: "maintenance", memoryType: "artifact", decisionMethod: "review" },
      { key: "rfc-consent", name: "RFC consent", activityType: "discussion", memoryType: "document", decisionMethod: "consent" },
      { key: "maintainer-decision", name: "Maintainer decision", activityType: "discussion", memoryType: "decision", decisionMethod: "custodian" },
    ],
    suggestedAgent: "Repository guide",
  },
  "agent-collective": {
    key: "agent-collective",
    name: "Agent Collective",
    description: "Coordinate multiple governed agents while keeping a separate Human Custodian.",
    labels: {
      members: "Actors",
      member: "Agent",
      human: "Custodian",
      agent: "Agent",
      service: "Service",
      guildActor: "Peer collective",
      memory: "Collective memory",
      memoryItem: "Context",
      remember: "Add context",
      activity: "Runs and activities",
      activityItem: "Mission",
      startActivity: "Start a mission",
      decisions: "Policy and approvals",
      decision: "Policy decision",
      history: "Run history",
      join: "Connect",
      leave: "Disconnect",
      participant: "Agent",
      coordinator: "Orchestrator",
    },
    roles: [
      { name: "Custodian", capabilities: unique(ADMINISTER_CAPABILITIES) },
      { name: "Orchestrator", capabilities: unique(PARTICIPATE_CAPABILITIES) },
      { name: "Specialist", capabilities: unique(PARTICIPATE_CAPABILITIES) },
    ],
    activityTypes: ["task", "investigation", "maintenance", "creation"],
    memoryTypes: ["agent_output", "fact", "data", "failure", "learning"],
    decisionMethods: ["policy", "hybrid"],
    dashboardIntents: ["review", "ask", "start", "remember", "members"],
    workflows: [
      { key: "policy-gated-run", name: "Policy-gated run", activityType: "task", memoryType: "agent_output", decisionMethod: "hybrid" },
    ],
    suggestedAgent: "Orchestrator",
  },
};

export const COLLECTIVE_TEMPLATES: readonly CollectiveTemplate[] = Object.values(templates);

export function collectiveTemplate(key: CollectiveTemplateKey): CollectiveTemplate {
  return templates[key];
}
